version: 0.0
os: linux
files:
  - source: /
    destination: /home/baryons
    overwrite: true

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: apache
    mode: 775
    type:
      - directory
      - file
